/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_dlib4android_dlibDetect */

#ifndef _Included_com_example_dlib4android_dlibDetect
#define _Included_com_example_dlib4android_dlibDetect
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dlib4android_dlibDetect
 * Method:    faceDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_example_dlib4android_dlibDetect_faceDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_example_dlib4android_dlibDetect
 * Method:    handleImage
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_dlib4android_dlibDetect_handleImage
  (JNIEnv *, jclass);

/*
 * Class:     com_example_dlib4android_dlibDetect
 * Method:    helloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_dlib4android_dlibDetect_helloWorld
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
